before_script:
    - apt-get update -qy
    - apt-get install -y python-imaging
    - apt-get install -y python-dev python-pip
    - apt-get install -y python-mysqldb
    - pip install --upgrade pip virtualenv virtualenvwrapper
    - virtualenv env
    - source env/bin/activate
    - pip install -r requirements.txt
    - cd src/
    - rm gp_cars/settings/production.py

django:
    script: 
    - python manage.py test
    only:
    - master